apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: srt-broker
  namespace: srt
spec:
  acceptors:
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
  console:
    expose: true
  deploymentPlan:
    image: 'registry.redhat.io/amq7/amq-broker:7.5'
    messageMigration: true
    size: 1
  upgrades:
    enabled: false
    minor: false
