apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: srt-broker
  namespace: srt
spec:
  acceptors:
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
    - expose: true
      name: stomp
      port: 5673
      protocols: stomp
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: false
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder