apiVersion: v1
kind: Secret
metadata:
  labels:
    app: infinispan-secret-identities
    clusterName: gamedata
    infinispan_cr: gamedata
  name: gamedata-jdg-credentials
  namespace: srt
type: Opaque
data:
  identities.yaml: Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGRldmVsb3BlcgogIHBhc3N3b3JkOiBlbkRZVUlmaThmTXBieUxKCi0gdXNlcm5hbWU6IG9wZXJhdG9yCiAgcGFzc3dvcmQ6IGsySHZHNGdZdjRnenhCOW8K
